### ISSUE TITLE
Add historical NREL datasets

### ISSUE THREAD

**Issue by AdamRJensen** [AssessingSolar/solarstations#100]
- [ ] https://www.nrel.gov/grid/solar-resource/noaa.html
- [ ] https://www.nrel.gov/grid/solar-resource/semrts.html
- [ ] https://www.nrel.gov/grid/solar-resource/west.html
- [ ] https://www.nrel.gov/grid/solar-resource/hbcu.html

**Comment by IoannisSifnaios** [comment]
- [ ] https://www.nrel.gov/grid/solar-resource/noaa.html
- [ ] https://www.nrel.gov/grid/solar-resource/semrts.html
- [ ] https://www.nrel.gov/grid/solar-resource/west.html
- [ ] https://www.nrel.gov/grid/solar-resource/hbcu.html
