### ISSUE TITLE
Add Chinese BSRN (CBSRN) stations

### ISSUE THREAD

**Issue by IoannisSifnaios** [AssessingSolar/solarstations#131]
[This paper](https://acp.copernicus.org/articles/23/4419/2023/acp-23-4419-2023.pdf) mentions seven stations in the CBSRN network.

![image](https://github.com/AssessingSolar/solarstations/assets/88548539/337f78cf-a09d-4eee-9333-7fe36fb9e305)

**Comment by AdamRJensen** [comment]
[Xilinhot is Tier 1](https://www.gruan.org/gruan/editor/documents/meetings/icm-1/pres/pres_049_Wu.pdf)

Also has albedo, IR, PAR; UV;

**Comment by IoannisSifnaios** [comment]
All statons are measuring GHI,DNI, and DHI. Some data are presented in [this paper](http://www.gyqx.ac.cn/CN/10.7522/j.issn.1000-0534.2012.00113) (in Chinese).
