### ISSUE TITLE
Add stations from the Indian Meteorological Department (IMD)

### ISSUE THREAD

**Issue by IoannisSifnaios** [AssessingSolar/solarstations#140]
Stations described [here](https://imdpune.gov.in/library/public/Solar%20Radiant%20Energy%20Over%20India.pdf) (station list on page 270).

**Comment by AdamRJensen** [comment]
It seems that India put out a tender in 2019 for new pyrheliometers and trackers: https://internal.imd.gov.in/tenders/20191009_td_224.pdf

There's a list of stations on page 35 of the above document mention 22 stations.

There's another tender document from 2023 that only lists 18 stations (page 30): https://internal.imd.gov.in/tenders/20230211_td_296.pdf

Many of the stations added in #141 are on the list, which means that most likely the majority are still in operation.

**Comment by AdamRJensen** [comment]
@IoannisSifnaios do you think it's the same stations as the Indian SRRA network described here (51 stations measuring GHI, DHI, DNI): https://www.researchgate.net/publication/275533998_Development_and_Test_of_Gap_Filling_Procedures_for_Solar_Radiation_Data_of_the_Indian_SRRA_Measurement_Network

**Comment by IoannisSifnaios** [comment]
Pune is the only Tier 1 station ([photo](https://www.imdpune.gov.in/SI/radiation_lab_new.html))
