### ISSUE TITLE
Check all hyperlinks

### ISSUE THREAD

**Issue by AdamRJensen** [AssessingSolar/solarstations#142]
We should write a script that checks that all the hyperlinks work.

**Comment by kandersolar** [comment]
This could be done in the sphinx build with something like [sphinx.builders.linkcheck.CheckExternalLinksBuilder](https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.linkcheck.CheckExternalLinksBuilder), or as a standalone CI job just using `requests`.  I'm inclined towards the latter so as to not slow down the documentation build.  @AdamRJensen any preference?

**Comment by AdamRJensen** [comment]
The latter sounds great! Didn't Echedey do something similar to this in pvlib recently?

**Comment by kandersolar** [comment]
Yes, but taking the sphinx approach: https://github.com/pvlib/pvlib-python/pull/1794

It makes more sense there since sphinx knows how to hunt down all the URLs in docstrings and such.  But here they are already in a nice tidy table for us :)

**Comment by echedey-ls** [comment]
I just came across this. I recommend the sphinx builder approach if you have intra-links since they also would get checked.
