### ISSUE TITLE
Add CanSIM stations (Canada)

### ISSUE THREAD

**Issue by IoannisSifnaios** [AssessingSolar/solarstations#178]
Described [here ](https://www.spectrafy.com/sites/default/files/2021-02/Deployment%20and%20early%20results%20from%20the%20CanSIM%20network%20CPV-13%202017.pdf) and [here](https://ieeexplore-ieee-org.proxy.findit.cvt.dk/stamp/stamp.jsp?tp=&arnumber=9518731)

**Comment by AdamRJensen** [comment]
Closing this as they're not using thermopile instruments
