### ISSUE TITLE
Add stations from Australian Bureau of Meteorology (BoM)

### ISSUE THREAD

**Issue by kandersolar** [AssessingSolar/solarstations#21]
I'm not immediately finding info on equipment listings, but making a note here for future reference.

http://www.bom.gov.au/climate/data/oneminsolar/about-IDCJAC0022.shtml
http://www.bom.gov.au/climate/data/oneminsolar/stations.shtml

**Comment by AdamRJensen** [comment]
For the PVPS Task 16 benchmark we used the following Australia stations

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/arajen/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/arajen/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


CFP | Australia | Australia | Adelaide | adelaide_airport | adelaide_airport   (Australia) | 01-01-2015 | 27-08-2020 | BoM | -34.9524 | 138.5196 | 2
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
CFP | Australia | Australia | Kalgoorlie_Boulder | kalgoorlie_boulder_airport | kalgoorlie_boulder_airport   (Australia) | 01-01-2015 | 27-08-2020 | BoM | -30.7847 | 121.4533 | 365.3
CFP | Australia | Australia | Geraldton | geraldton_airport | geraldton_airport   (Australia) | 01-01-2015 | 27-08-2020 | BoM | -28.8047 | 114.6989 | 29.7
CFP | Australia | Australia | Rockhampton | rockhampton_aero | rockhampton   (Australia) | 01-01-2015 | 27-08-2020 | BoM | -23.3753 | 150.4775 | 10.4
CFP | Australia | Australia | Learmonth   Airport | learmonth_airport | learmonth_airport   (Australia) | 01-01-2015 | 27-08-2020 | BoM | -22.2406 | 114.0967 | 5
CFP | Australia | Australia | Townsville | townsville_aero | townsville   (Australia) | 01-01-2015 | 27-08-2020 | BoM | -19.2483 | 146.7661 | 4.34
CFP | Australia | Australia | Broome | broome_airport | broome_airport   (Australia) | 01-01-2015 | 27-08-2020 | BoM | -17.9475 | 122.2353 | 7.42
CFP | Australia | Australia | Darwin | darwin_airport | darwin_airport   (Australia) | 01-01-2015 | 27-08-2020 | BoM | -12.4239 | 130.8925 | 30.4
CFP | Australia | Australia |   | dwn | Darwin   Met Office (Australia) | 01-01-2015 | 31-12-2018 | BSRN | -12.424 | 130.8925 | 32
CFP | Australia | Cocos   Islands | Cocos   Island | cocos_island_airport | cocos_island   (Australia) | 01-01-2015 | 27-08-2020 | BoM | -12.1892 | 96.8344 | 3
CFP | Australia | Cocos   Islands | Cocos   Island | COC | Cocos   Island | 01-01-2015 | 31-12-2018 | BSRN | -12.193 | 96.835 | 6
CFP | Australia | New Zealand | Lauder | LAU | Lauder | 01-01-2015 | 31-12-2018 | BSRN | -45.045 | 169.689 | 350



</body>

</html>

**Comment by AdamRJensen** [comment]
Here's some text from my correspondence with BoM:
> http://www.bom.gov.au/climate/data/oneminsolar/stations.shtml  The current network of stations only have data to the end of 2021.  Data are usually processed 2 months after each full quarter, however due to staffing and COVID (etc) this is more likely to be done 2 months after each half year. The (sparse) network of surface based stations has direct, diffuse, global, direct of a horizontal surface and terrestrial mean.

**Comment by IoannisSifnaios** [comment]
BOM had also an older network called SECVI that operated from 1993-1996. However, it was not possible to find information on these stations.

![image](https://github.com/AssessingSolar/solarstations/assets/88548539/2ad84d54-2aac-4fd5-ad99-0abc7b7dd527)

**Comment by IoannisSifnaios** [comment]
BOM hasn't updated its webpage after 2021. Thus, some stations are reported to have stopped operating in 2021, while this might not be true (i.e., Broome, Cape Grim, Darwin, Melbourne, Rockhampton).

@AdamRJensen has contacted BOM about this.
