### ISSUE TITLE
SURFRAD station coordinates could be improved

### ISSUE THREAD

**Issue by kanderso-nrel** [AssessingSolar/solarstations#22]
It seems that the current coordinates for the Bondville station are some ~1.7 km away from the correct coordinates, which is large enough to potentially make a difference in some applications (e.g. satellite-ground comparisons).  Bondville's elevation is also a bit different from NOAA's value.  The coordinates for the other stations are also not as precise as they could be.  I suggest switching to the coordinates listed on this page: https://gml.noaa.gov/grad/surfrad/sitepage.html

**Comment by AdamRJensen** [comment]
@kanderso-nrel Thank you for raising this issue 😄
