### ISSUE TITLE
Alternate table of content titles not rendering

### ISSUE THREAD

**Issue by AdamRJensen** [AssessingSolar/solarstations#263]
The alternate titles specified in the docs/_toc.yml file are not rendering, even though they seem to be correctly formatted according to the documentation: https://jupyterbook.org/en/stable/structure/configure.html#specify-alternate-titles

Related to https://github.com/jupyter-book/jupyter-book/issues/486

**Comment by AdamRJensen** [comment]
@kandersolar if you could confirm that this is indeed not a solvable issue that would be helpful

**Comment by kandersolar** [comment]
It is solvable, the notebooks just need to have a single top-level header.  For example, the BSRN one starts working if you demote `References` to a second-level header.
