### ISSUE TITLE
Other data sources

### ISSUE THREAD

**Issue by AdamRJensen** [AssessingSolar/solarstations#28]
It would be nice with a page with a list of alternative sources of data (lower quality):

[Research stations in Antarctica](https://www.grida.no/resources/7148)
[Ladybug - collection of EPW/TMY weather files](https://www.ladybug.tools/epwmap/)
[Overview of reanalysis datasets](https://reanalyses.org)

[CANSIM](https://aip.scitation.org/doi/10.1063/1.5001451) - Canadian network with 7 stations measuring spectral irradiance using Spectrafy sensors.

[Eye2Sky network of all-sky cameras near Oldenburg, Germany](https://www.dlr.de/content/en/images/2019/4/the-eye2sky-measurement-network-will-comprise-34-stations-when-complete.html) [other link](https://www.dlr.de/ve/en/desktopdefault.aspx/tabid-17889/28318_read-73347/)

Oklahoma Mesonet (weather stations with LI-COR pyranometers): [website](https://www.mesonet.org/index.php/weather/map/solar_radiation/solar_radiation_satellite), [paper](https://doi.org/10.1175/1520-0426(2000)017%3C0474:QAPITO%3E2.0.CO;2)

German Weather Services - Deutscher Wetterdienst (DWD) also operates a network of 25 sites measuring global horizontal irradiance and diffuse irradiance with thermopile pyranometers with a resolution of 10 minutes.

https://natural-resources.canada.ca/energy/renewable-electricity/solar-photovoltaic/18409

https://www.fdr.uni-hamburg.de/record/12548

http://globalsolaratlas.info/

**Comment by IoannisSifnaios** [comment]
There is also [this report](https://atmosphere.copernicus.eu/sites/default/files/custom-uploads/EQC-solar/CAMS2_73_2021SC1-D1.4.1-2022_ground_catalogue_202212_v2_APPROVED_Ver1.pdf) from MINES Paris including some stations.
