### ISSUE TITLE
Add ESMAP / World Bank stations

### ISSUE THREAD

**Issue by AdamRJensen** [AssessingSolar/solarstations#35]
Energy Sector Management Assistance Program (ESMAP) is a partnership led by the World Bank, and has historically funded solar radiation monitoring campaigns in developing countries.

An overview of the solar radiation monitoring stations can be found here (see also screen-shot below): https://energydata.info/dataset/world-solar-stations-inventory-2017

It seems some of these stations are the same as those listed on the Global Solar Atlas site: https://globalsolaratlas.info/solar-measurement

![image](https://user-images.githubusercontent.com/39184289/182629457-282cbd2c-7ebb-4523-a0e6-61151af9977c.png)

**Comment by IoannisSifnaios** [comment]
@AdamRJensen some information on the instruments used in the ESMAP stations can be found [here](https://hal.science/hal-04071393/document). 

Table 3 has a nice summary of the used instruments.
