### ISSUE TITLE
Reginal Test Centers (RTC) - USA

### ISSUE THREAD

**Issue by AdamRJensen** [AssessingSolar/solarstations#39]
The [Regional Test Centers](https://rtc.sandia.gov/) consists of five sites for testing PV outdoors for different climates.

- [ ] **Albuquerque, NM**
> The NM RTC is co-located with Sandia’s Photovoltaic Systems Evaluation Laboratory, which is a multiple-user facility that conducts research on emerging PV technologies and supports the detailed characterization and performance analysis of modules and components.

- [ ] **Golden, CO**
> The CO RTC is co-located with the National Renewable Energy Laboratory’ Outdoor Test Facility.

- [ ] **Calumet, MI**
> The Michigan Regional Test Center (MI RTC) is located in Calumet, Michigan adjacent to the Advanced Power Systems Center at Michigan Technological University.

- [ ] **Cocoa, FL**
> The FL RTC is located on a 10-acre site owned by the Florida Solar Energy Center in Cocoa, FL, where the climate is consistently hot and humid.
latitude=28.40509, longitude=-80.77090

- [ ] **Henderson, NV**
> Located less than 20 miles south of Las Vegas, this site is defined by high irradiance, high heat and limited precipitation. Site Partners: the University of Nevada, Las Vegas and the Southern Nevada Water Authority (SNWA).

![image](https://user-images.githubusercontent.com/39184289/183281733-e98ab393-b8ed-4478-a10b-38a16fb37f45.png)

**Comment by AdamRJensen** [comment]
Photo of the RTC in Cocoa
![image](https://user-images.githubusercontent.com/39184289/183282818-5869137a-01b0-4539-ad1b-b4cd014f8da7.png)

**Comment by kandersolar** [comment]
@AdamRJensen my understanding is that the RTC irradiance datasets are not public, nor are there any plans to make them public.  A few datasets seem to have "leaked out" through collaborators, but to my knowledge none of them include the base irradiance components.  

I see "not available" is an option for [data availability](https://solarstations.org/station_requirements.html#station-metadata).  Does that mean we should still add the RTC stations to the list?

**Comment by AdamRJensen** [comment]
Interesting! My impression was that if you contacted them, they would be willing to share data (I forget who I talked to, think it was a woman at Sandia).

But yes everything gets added! 😄 For now you can just put "Not available"
