### ISSUE TITLE
Generate additional metadata

### ISSUE THREAD

**Issue by AdamRJensen** [AssessingSolar/solarstations#9]
It would be nice to provide additional metadata for the stations, including:
- [x] Climate classification ([Köppen Geiger](https://en.wikipedia.org/wiki/K%C3%B6ppen_climate_classification)) #121 
- [ ] Annual irradiance (just GHI or all three components?)
- [x] Continent (useful for sorting the station listing and statistics) #203
- ~~PV Climate Zones (mentioned by Kevin below)~~

It would be optimal to automatically generate this metadata. The annual irradiance could come from a provider with global coverage, e.g., [NASA Power](https://power.larc.nasa.gov/) or the Global Solar Atlas. The continent could be determined based on latitude/longitude.

Additional things to consider:
* In this [paper](http://les.edu.uy/FRS/extras/Gueymard_RA_Difusa_SE2015.pdf) by Gueymard only four climate classifications were used. (will not add this)

**Comment by kanderso-nrel** [comment]
You may also be interested in PV Climate Zones: https://pvtools.lbl.gov/pv-climate-stressors and https://github.com/toddkarin/pvcz

**Comment by AdamRJensen** [comment]
Thanks @kanderso-nrel. Is PV Climate Zone actually something that is used?

I noticed that the first link also shows Köppen Geiger climate zones, so perhaps I can get some inspiration for how to program that.

**Comment by kanderso-nrel** [comment]
It's a relatively new development (especially compared w/ something like KG), but yes it is getting used: https://scholar.google.com/scholar?cites=7515697662620840254&as_sdt=4005&sciodt=0,6&hl=en

**Comment by kandersolar** [comment]
This package has high-resolution KG classification lookup: https://pypi.org/project/kgcPy/
